config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  get 'home/index'
  post 'home/guest_sign_in'
  resources :users, :only => [:show, :edit, :update, :destroy]
  resources :books, :only => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get "search"
    end
  end
  resources :comments, :only => [:create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_one_attached :image
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def search
    @results = @search.result.includes(:image_attachment)
  end

  def guest_sign_in
    user = User.find_or_create_by!(name: "guestuser", email: "guestuser@example.com") do |u|
      u.password = "hogehoge"
    end
    sign_in user
    flash[:notice] = "ゲストユーザーとしてログインしました。"
    redirect_to root_path
  end

  private

  def set_search
    @search = Book.ransack(params[:q])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def show
    @book = Book.find(params[:id])
    @rakuten_books = RakutenWebService::Books::Book.search(title: @book.title)
    @comment = Comment.new
    @book_comments = @book.comments.includes([:user])
  end

  def new
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "本を登録しました。"
      redirect_to book_path(@book.id)
    else
      flash.now[:alert] = "本を登録できませんでした。"
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      flash[:alert] = "本の登録ユーザーでないため、本を編集できません。"
      redirect_to root_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "本の情報を更新しました。"
      redirect_to book_path(@book.id)
    else
      flash.now[:alert] = "本の情報を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.destroy
      flash[:notice] = "本を削除しました。"
      redirect_to user_path(@user.id)
    else
      flash[:alert] = "本を削除できませんでした。"
      redirect_to user_path(@user.id)
    end
  end

  def rakuten_search
    if params[:keyword]
      @books = RakutenWebService::Books::Book.search(title: params[:keyword])
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :user_id, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:edit]

  def create
    @book = Book.find(comment_params[:book_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "コメントを投稿しました。"
    else
      flash[:alert] = "コメントを投稿できませんでした。"
    end
    redirect_to book_path(@book.id)
  end

  def edit
    @comment = Comment.find(params[:id])
    if @comment.user_id != current_user.id
      flash[:alert] = "投稿者でないため、コメントを編集できません。"
      redirect_to root_path
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "コメントを更新しました。"
      redirect_to book_path(@comment.book.id)
    else
      flash.now[:alert] = "コメントを更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = "コメントを削除しました。"
      redirect_to user_path(current_user.id)
    else
      flash[:alert] = "コメントを削除できませんでした。"
      redirect_to root_path(current_user.id)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :book_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit]

  def show
    @user = User.find(current_user.id)
    @books = @user.books.includes([:image_attachment])
    @comments = @user.comments.includes(:book)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました。"
      redirect_to home_index_path
    else
      flash.now[:alert] = "ユーザー情報を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user.id)
    if @user.destroy
      flash[:notice] = "ユーザーを削除しました。"
      redirect_to root_path
    else
      flash[:alert] = "ユーザーを削除できませんでした。"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.hml.erb
edit

app/views/books/edit.html.erb
<div class="container edit-container text-center mt-5 bg-light border border-2">
  <h2 class="pt-5">本の編集</h2>
  <div class="form-container mb-5 pb-5">
    <%= form_with(model: @book, local: true) do |form| %>
      <%= render "shared/error_messages", model: form.object %>
      <%= render "shared/book_icon" %><br>

      <%= form.label :title, "タイトル", class: "mt-3 mb-2" %><br>
      <%= form.text_field :title, class: "col-8 col-sm-6 col-md-5 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :author, "著者", class:"mt-3 mb-2" %><br>
      <%= form.text_field :author, class: "col-8 col-sm-6 col-md-5 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :description, "説明文", class: "mt-3 mb-2" %><br>
      <%= form.text_area :description, class: "col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :image, "画像", class: "mt-3 mb-2" %><br>
      <%= form.file_field :image, class: "col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.hidden_field :user_id, value: current_user.id %>

      <%= form.submit "本の更新", class: "btn btn-success col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %><br>
    <% end %>
    <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container text-center mt-5 bg-light border border-2">
  <h2 class="pt-5">本の登録</h2>
  <div class="form-container mb-5 pb-5">
    <%= form_with(model: @book, local: true) do |form| %>
      <%= render "shared/error_messages", model: form.object %>

      <%= form.label :title, "タイトル", class: "mt-3 mb-2" %><br>
      <%= form.text_field :title, class: "col-8 col-sm-6 col-md-5 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :author, "著者", class: "mt-3 mb-2" %><br>
      <%= form.text_field :author, class: "col-8 col-sm-6 col-md-5 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :description, "説明文", class: "mt-3 mb-2" %><br>
      <%= form.text_area :description, class: "col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :image, "画像", class: "mt-3 mb-2" %><br>
      <%= form.file_field :image, class: "col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.hidden_field :user_id, value: current_user.id %>

      <%= form.submit "本の登録", class: "btn btn-success col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %><br>
    <% end %>
    <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %>
  </div>
</div>

app/views/books/search.html.erb
<div class="container text-center bg-light border border-2 my-5 p-md-5">
  <h2>検索結果：<%= @results.size %>件</h2>
  <table class="search-book-table">
    <thead>
      <tr>
        <th class="col-4 xs-d-none">写真</th>
        <th class="col-4">タイトル</th>
        <th class="col-2">著者</th><br>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td class="col-4 xs-d-none">
            <% if result.image.attached? %>
              <%= link_to image_tag(result.image, class: "img-fluid p-md-2"), book_path(result.id) %>
            <% else %>
              <%= link_to image_tag("noimage-book.jpg", class: "img-fluid p-md-2"), book_path(result.id)%>
            <% end %>
          </td>
          <td class="col-4 text-break"><%= link_to(result.title, book_path(result.id)) %></td>
          <td class="col-2 text-break"><%= result.author %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<div class="container my-5">
  <div class="book-show-container text-center my-5 border border-2 bg-light py-4">
    <h2 class="my-4 text-center">本の情報</h2>
    <%= render "shared/book_icon" %>
    <div class="my-5 ">
      <div class="mx-auto my-md-5 py-2 px-md-5 border border-1 bg-white w-75">
        <p class="font-24px">タイトル</p>
        <p class="text-break pb-2"><%= @book.title %></p>
        <p class="font-24px">著者</p>
        <p class="text-break pb-2"><%= @book.author %></p>
        <p class="font-24px">説明文</p>
        <p class="text-start text-break pb-2"><%= @book.description %></p>
      </div>
      <div class="my-5 m-md-5 py-3 px-md-5 border border-1 bg-white">
        <p class="font-24px">本の登録者</p>
        <p class="text-break"><%= @book.user.name %></p>
      </div>
      <% if @rakuten_books.first && @rakuten_books.first.title == @book.title %>
        <p class="mt-4">楽天リンク：<%= link_to @rakuten_books.first.title, @rakuten_books.first.item_url %></p>
      <% end %>
      <% if user_signed_in? && @book.user_id == current_user.id %>
        <%= link_to "編集", edit_book_path(@book.id), class: "btn btn-primary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 my-4" %><br>
      <% end %>
      <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 my-4" %>
    </div>
  </div>
  <div class="comment-container w-100 mx-auto my-5 text-center border border-2 bg-light p-4">
    <h3 class="my-5">コメント一覧(<%= @book.comments.size %>件)</h3>
    <% if @book.comments.size != 0 %>
      <table class="mx-auto">
        <thead>
          <tr>
            <th class="col-4">投稿者</th>
            <th class="col-8">コメント</th>
          </tr>
        </thead>
        <tbody>
        <% @book_comments.each do |comment| %>
          <tr>
            <td class="col-4 text-break"><%= comment.user.name %></td>
            <td class="col-8 text-break"><%= comment.comment %><br></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
    <% if user_signed_in? %>
      <div class="form-container my-3 py-3">
        <%= form_with(model: @comment, local: true, url: comments_path) do |form| %>
          <%= render "shared/error_messages", model: form.object %>
          <div class="text-area">
            <%= form.label :comment, "コメント", class: "mb-4" %><br>
            <%= form.text_area :comment, class: "col-12 col-sm-9 col-lg-6 h-150px" %><br>
          </div>
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.hidden_field :book_id, value: @book.id %>
          <%= form.submit "投稿", class: "btn btn-success col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-4" %><br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container edit-container text-center mt-5 bg-light border border-2">
  <h2 class="pt-5">コメントの編集</h2>
  <div class="form-container mb-5 pb-5">
    <%= form_with(model: @comment, local: true) do |form| %>
      <%= render "shared/error_messages", model: form.object %>
      <%= form.label :comment, "コメント", class: "mt-3 mb-2" %><br>
      <%= form.text_area :comment, class: "h-100px col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.hidden_field :user_id, value: @comment.user_id %>
      <%= form.hidden_field :book_id, value: @comment.book_id %>

      <%= form.submit "コメントの更新", class: "btn btn-success col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %><br>
    <% end %>
    <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-5" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="position-relative text-center">
    <%= image_tag "main-image.jpg", class: "mt-5 w-100 mw-1000px" %>
    <span class="position-absolute main-word-position text-white font-bold xs-16px sm-24px md-32px">あなたの好きを、誰かの好きに。</span>
  </div>
  <div class="mt-5 py-4 bg-green">
    <h2 class="md-32px text-center mb-2">BookLoverとは?</h2>
    <p class="md-24px lh-lg text-start py-sm-2 px-2 px-sm-4">
    BookLoverは好きな本を共有できるサイトです。「自分の好きな本を伝えたい」「他の人がどんな本を好きなのか知りたい」という
    想いを実現するため作成しました。<br>
    あなたも好きな本を登録してみませんか。
    </p>
  </div>
   <div class="text-center mt-5">
    <h2 class="mt-5 mb-3 font-bold">おすすめジャンル</h2>
    <div class="d-flex flex-wrap">
      <div class="position-relative my-3 px-lg-3 mx-auto col-9 col-lg-6">
        <%= link_to (image_tag "recommend-nobel.jpg", alt: "小説", class: "w-100"), search_books_path(q: {title_or_author_or_description_cont: "小説"}) %>
        <span class="position-absolute recommend-position bg-dark text-white md-24px">小説</span>
      </div>
      <div class="position-relative my-3 px-lg-3 mx-auto col-9 col-lg-6">
        <%= link_to (image_tag "recommend-business.jpg", alt: "ビジネス", class: "w-100"), search_books_path(q: {title_or_author_or_description_cont: "ビジネス"}) %>
        <span class="position-absolute recommend-position bg-dark text-white md-24px">ビジネス</span>
      </div>
      <div class="position-relative my-3 px-lg-3 mx-auto col-9 col-lg-6">
        <%= link_to (image_tag "recommend-health.jpg", alt: "健康", class: "w-100"), search_books_path(q: {title_or_author_or_description_cont: "健康"}) %>
        <span class="position-absolute recommend-position bg-dark text-white md-24px">健康</span>
      </div>
      <div class="position-relative my-3 px-lg-3 mx-auto col-9 col-lg-6">
        <%= link_to (image_tag "recommend-money.jpg", alt: "お金", class: "w-100"), search_books_path(q: {title_or_author_or_description_cont: "お金"}) %>
        <span class="position-absolute recommend-position bg-dark text-white md-24px">お金</span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookLover</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="d-block w-100">
      <%= render 'shared/navbar' %>
    </header>
    <%= render 'shared/notice_alert' %>
    <%= yield %>
    <footer class="mt-5 h-100px d-flex justify-content-center align-items-center">
      <%= link_to "BookLover", home_index_path, class: "footerlogo" %>
    </footer>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_book_icon.html.erb
<% if @book.image.attached? %>
  <%= image_tag @book.image, class: "img-fluid" %>
<% else %>
  <%= image_tag "noimage-book.jpg", class: "img-fluid" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <nav class="navbar navbar-light bg-light px-4">
    <div>
      <h1><%= link_to "BookLover", home_index_path, class: "navbar-brand" %></h1>
    </div>
    <div>
      <%= search_form_for @search, url: search_books_path do |f| %>
        <%= f.search_field :title_or_author_or_description_cont, placeholder: "本を検索", class: "search-book" %>
        <%= f.submit "検索", class: "xs-d-none" %>
      <% end %>
    </div>
    <div>
      <span class="xs-d-none mx-2"><%= current_user.name %></span>
      <span class="xs-d-none mx-2"><%= render "shared/user_icon" %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-end" id="navbarNav" aria-expanded="true">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <%= link_to "パスワード編集", edit_user_registration_path(current_user.id), class: 'btn btn-outline-primary mt-2 mb-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "名前、アイコン編集", edit_user_path(current_user.id), class: 'btn btn-outline-info mb-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "本の登録", new_book_path, class: 'btn btn-outline-success mb-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "ユーザー情報", user_path(current_user.id), class: 'btn btn-outline-secondary mb-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark mb-2' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<% else %>
  <nav class="navbar navbar-light navbar-expand-md bg-light px-4 justify-content-between">
    <div>
      <h1><%= link_to "BookLover", home_index_path, class: "navbar-brand" %></h1>
    </div>
    <div>
      <%= search_form_for @search, url: search_books_path do |f| %>
        <%= f.search_field :title_or_author_or_description_cont, placeholder: "本を検索", class: "search-book" %>
        <%= f.submit "検索", class: "xs-d-none" %>
      <% end %>
    </div>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-end" id="navbarNav" aria-expanded="true">
        <ul class="nav navbar-nav navbar-right text-end">
          <li class="nav-item active">
            <%= link_to "ゲストログイン", home_guest_sign_in_path, method: :post, class: 'btn btn-dark m-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary m-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-secondary m-2' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_notice_alert.html.erb
<% if notice %>
  <p class="alert alert-primary text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

app/views/shared/_user_icon.html.erb
<% if current_user.image.attached? %>
  <%= image_tag current_user.image, class: "rounded-circle img-fluid" %>
<% else %>
  <%= image_tag "noimage-user.jpg", class: "rounded-circle img-fluid" %>
<% end %>

app/views/users/edit.html.erb
<div class="container user-container text-center mt-5 bg-light border border-2">
  <h2 class="py-4 ">名前、アイコン編集</h2>
  <%= render "shared/user_icon" %>
  <div class="form-container mb-5 pb-5">
    <%= form_with model:@user do |form| %>
      <%= form.label :name, "名前", class: "mt-3 mb-2 xs-1rem" %><br>
      <%= form.text_field :name, class: "col-10 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.label :image, "アイコン", class: "mt-3 mb-2 xs-1rem" %><br>
      <%= form.file_field :image, class: "col-10 col-sm-8 col-md-6 col-lg-4 col-xl-3 mb-2" %><br>

      <%= form.submit "更新", class: "btn btn-success col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-4" %><br>
      <%= link_to "アカウント削除", user_path(current_user.id), method: :delete, 
          class: 'btn btn-danger col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-4', data: {confirm: "本当にアカウントを削除してよろしいですか？" } %><br>
    <% end %>
    <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary col-6 col-sm-5 col-md-4 col-lg-3 col-xl-2 mt-4" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container user-container text-center my-5">
  <div class="my-5 border border-2 bg-light py-4">
    <h2 class="mt-4">ユーザー情報</h2>
    <div class="col-6 col-sm-4 mx-auto">
      <%= render "shared/user_icon" %>
    </div>
    <%= form_with model:@user do |form| %>
      <%= form.label :name, "名前", class: "mt-3 mb-2" %><br>
      <%= form.text_field :name, class: "col-8 col-sm-6 col-md-5 col-lg-4 col-xl-3  mt-3 mb-5", disabled: true %><br>
    <% end %>
    <%= link_to "名前、アイコン編集", user_path(current_user.id), class: "btn btn-primary" %><br>
    <%= link_to "トップページに戻る", home_index_path, class: "btn btn-secondary my-3" %>
  </div>
  <div class="book-container bg-light border border-2 my-5 p-md-5">
    <h2>登録した本の一覧</h2>
    <table class="user-show-table">
      <thead>
        <tr>
          <th class="col-2 sm-d-none">写真</th>
          <th class="col-2">タイトル</th>
          <th class="col-2 xs-d-none">著者</th>
          <th class="col-2 xs-d-none">説明文</th>
          <th class="col-1">編集</th>
          <th class="col-1">削除</th><br>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td class="sm-d-none">
              <% if book.image.attached? %>
                <%= link_to image_tag(book.image, class: "img-fluid p-2"), book_path(book.id) %>
              <% else %>
                <%= link_to image_tag("noimage-book.jpg", class: "img-fluid p-2"), book_path(book.id)%>
              <% end %>
            </td>
            <td class="text-break"><%= link_to(book.title, book_path(book.id)) %></td>
            <td class="xs-d-none text-break"><%= book.author %></td>
            <td class="xs-d-none text-break"><%= book.description %></td>
            <td><%= link_to "編集", edit_book_path(book.id) %></td>
            <td><%= link_to "削除", book_path(book.id), method: :delete, data: {confirm: "本当に本を削除してよろしいですか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="comment-container bg-light border border-2 my-5 p-md-5 ">
    <h2>投稿したコメント一覧</h2><br>
    <table class="user-show-table">
      <thead>
        <tr>
          <th class="col-2 sm-d-none">写真</th>
          <th class="col-2 xs-d-none">タイトル</th>
          <th class="col-2">コメント</th>
          <th class="col-1">編集</th>
          <th class="col-1">削除</th><br>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td class="sm-d-none">
              <% if comment.book.image.attached? %>
                <%= link_to image_tag(comment.book.image, class: "img-fluid p-2"), book_path(comment.book.id) %>
              <% else %>
                <%= link_to image_tag("noimage-book.jpg", class: "img-fluid p-2"), book_path(comment.book.id)%>
              <% end %>
            </td>
            <td class="xs-d-none text-break"><%= link_to(comment.book.title, book_path(comment.book.id)) %></td>
            <td class="text-break"><%= comment.comment %></td>
            <td><%= link_to "編集", edit_comment_path(comment.id) %></td>
            <td><%= link_to "削除", comment_path(comment.id), method: :delete, data: {confirm: "本当にコメントを削除してよろしいですか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>